name: .NET API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore .\\WebAPI\\
    - name: Build
      run: dotnet build .\\WebAPI\\ --no-restore
    - name: Test
      run: dotnet test .\\WebAPI\\ --no-build --verbosity normal
